### PR TITLE
use my api for FILENAME

### PR DESCRIPTION
**Pull request by hoholee12**
use my api for FILENAME
- to ( ~Deic)
  can you elaborate what kind of error you are getting in checkerz?
  (~hoholee12)
  some logs or screenshots would be nice.

### CODE REVIEW

**Comment by DeicPro** [comment]
bb_apg_2 not found every time is running $chk random msg

**Comment by DeicPro** [comment]
every time is running $chk random msg

**Comment by hoholee12** [comment]
plz wait, im trying to reupload everything:P

**Comment by DeicPro** [comment]
pizza didnt gave you rw perms?

edit-
ok no, first need is in the team lol

edit2-
@hoholee12 
left many? I have that fix a 2 important things xD

**Comment by DeicPro** [comment]
ok no, first need is in the team lol

**Comment by DiamondBond** [comment]
@hoholee12 youve been allowed to r/w to files directly :D
@DeicPro add curl to the busybox applet checker :)

**Comment by hoholee12** [comment]
thanks:D @DiamondBond

**Comment by DeicPro** [comment]
@DiamondBond to download curl binary say? if that im add busybox 1.23.2 download and install too

**Pull request closed without merging**
